"""Generate ams2_ai/data/track_meta.json from AMS2 wiki layout names."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TRACKS_JSON = ROOT / "ams2_ai" / "data" / "tracks.json"
OUT_JSON = ROOT / "ams2_ai" / "data" / "track_meta.json"

# venue, layout — sourced from Automobilista 2 Wiki (Tracks and Layouts)
META: dict[str, tuple[str, str]] = {
    "Adelaide_Historic": ("Adelaide", "Historic 1988"),
    "Adelaide_Modern": ("Adelaide", "Grand Prix"),
    "Adelaide_Modern_STT": ("Adelaide", "STT"),
    "Ascurra_Dirt": ("Ascurra", "Dirt"),
    "Ascurra_RX": ("Ascurra", "Rallycross"),
    "Azure_Circuit_2021": ("Azure Circuit", "Grand Prix"),
    "Bathurst_1983": ("Bathurst", "1983"),
    "Bathurst_2020": ("Bathurst", "2020"),
    "Barcelona_1991": ("Barcelona", "1991"),
    "Barcelona_GP_1999": ("Barcelona", "GP 1999"),
    "Barcelona_GP_2001": ("Barcelona", "GP 2001"),
    "BrandsHatch_GP": ("Brands Hatch", "Grand Prix"),
    "BrandsHatch_Indy": ("Brands Hatch", "Indy"),
    "Brasilia_Full": ("Brasília", "Full"),
    "Brasilia_Outer": ("Brasília", "Outer"),
    "Buenos_Aires_Circuito_6": ("Buenos Aires", "Circuito No. 6"),
    "Buenos_Aires_Circuito_6T": ("Buenos Aires", "Circuito No. 6S"),
    "Buenos_Aires_Circuito_7": ("Buenos Aires", "Circuito No. 7"),
    "Buenos_Aires_Circuito_8": ("Buenos Aires", "Circuito No. 8"),
    "Buenos_Aires_Circuito_9": ("Buenos Aires", "Circuito No. 9"),
    "Buenos_Aires_Circuito_12": ("Buenos Aires", "Circuito No. 12"),
    "Buenos_Aires_Circuito_15": ("Buenos Aires", "Circuito No. 15"),
    "Buskerud_Long": ("Buskerud", "Kart Long"),
    "Buskerud_Short": ("Buskerud", "Kart"),
    "CadwellPark": ("Cadwell Park", "Full"),
    "CampoGrande1": ("Campo Grande", "Full"),
    "Cascavel2": ("Cascavel", "Full"),
    "Cascais": ("Cascais", "Grand Prix"),
    "Cascais_1988": ("Cascais", "Historic 1988"),
    "Cascais_Alternate": ("Cascais", "Alternate"),
    "Circuit_de_Catalunya_GP": ("Barcelona", "Catalunya GP"),
    "Circuit_de_Catalunya_GP_NC": ("Barcelona", "Catalunya GP (No Chicane)"),
    "Circuit_de_Catalunya_NATL_NC": ("Barcelona", "Catalunya National"),
    "Circuit_de_Catalunya_RX": ("Barcelona", "Catalunya Rallycross"),
    "Cleveland_GP": ("Cleveland", "Grand Prix"),
    "Cleveland_STT": ("Cleveland", "STT"),
    "Cordoba_GP": ("Córdoba", "TC"),
    "Cordoba_International": ("Córdoba", "No. 4"),
    "Cordoba_NATL": ("Córdoba", "No. 2"),
    "CopaSaoPauloStage2": ("Granja Viana", "Copa São Paulo Stage 2"),
    "CuritibaInternacional": ("Curitiba", "Full"),
    "Curitiba_outer": ("Curitiba", "Outer"),
    "CurveloLong": ("Curvelo", "Long"),
    "CurveloShort": ("Curvelo", "Short"),
    "Daytona_Speedway_Tri_Oval": ("Daytona", "NASCAR Tri-Oval"),
    "Daytona_Road_Course": ("Daytona", "Sports Car Course"),
    "Daytona_Nascar_Road_Course": ("Daytona", "NASCAR Road Course"),
    "Donington_GP": ("Donington Park", "Grand Prix"),
    "Donington_Nat": ("Donington Park", "National"),
    "Fontana_OVAL": ("Fontana", "Oval"),
    "Fontana_OVAL_Historic": ("Fontana", "Oval Historic"),
    "Fontana_SCC": ("Fontana", "Sports Car Course"),
    "Foz_RX": ("Foz", "Rallycross"),
    "Galeao_Airport": ("Galeão Airport", "Full"),
    "Gateway_OVAL": ("Gateway", "Oval"),
    "Gateway_RC1": ("Gateway", "Road Course (Long)"),
    "Gateway_RC2": ("Gateway", "Road Course (Short)"),
    "GoianiaMixed": ("Goiânia", "Mixed"),
    "GoianiaOuter": ("Goiânia", "External"),
    "GoianiaShort": ("Goiânia", "Short"),
    "GranjaVianaKart101": ("Granja Viana", "Kart 101"),
    "GranjaVianaKart102": ("Granja Viana", "Kart 102"),
    "GranjaVianaKart121": ("Granja Viana", "Kart 121"),
    "Guapore": ("Guaporé", "Full"),
    "Guapore_STT": ("Guaporé", "STT"),
    "Hockenheim_GP": ("Hockenheimring", "Grand Prix"),
    "Hockenheim_ShortA": ("Hockenheimring", "Short A"),
    "Hockenheim_ShortB": ("Hockenheimring", "Short B"),
    "Hockenheim_National": ("Hockenheimring", "National"),
    "Hockenheim_2001": ("Hockenheimring", "Historic 2001"),
    "Hockenheim_1988": ("Hockenheimring", "Historic 1988"),
    "Hockenheim_1988_short": ("Hockenheimring", "Historic 1988 Short"),
    "Hockenheim_1977": ("Hockenheimring", "Historic 1977"),
    "Hockenheim_RX": ("Hockenheimring", "Rallycross"),
    "Hockenheim_STT": ("Hockenheimring", "STT"),
    "Hungaroring_GP_2025": ("Hungaroring", "Grand Prix"),
    "Ibarra2": ("Ibarra", "Yahuarcocha"),
    "Ibarra_Reverse": ("Ibarra", "Yahuarcocha Reverse"),
    "Ibarra_STT": ("Ibarra", "Yahuarcocha STT"),
    "Imola_GP_2018": ("Imola", "Grand Prix"),
    "Imola_GP_1972": ("Imola", "Historic 1972"),
    "Imola_GP_1988": ("Imola", "Historic 1988"),
    "Imola_GP_2001": ("Imola", "Historic 2001"),
    "Imola_GP_2005": ("Imola", "Historic 2005"),
    "Indianapolis_2001_Oval": ("Indianapolis", "Oval 2001"),
    "Indianapolis_2001_RC": ("Indianapolis", "Road Course 2001"),
    "Indianapolis_2022_Oval": ("Indianapolis", "Oval"),
    "Indianapolis_2022_RC": ("Indianapolis", "Road Course"),
    "Interlagos_1991": ("Interlagos", "1991"),
    "Interlagos_1993": ("Interlagos", "1993"),
    "Interlagos_GP": ("Interlagos", "Grand Prix"),
    "Interlagos_SCB": ("Interlagos", "Stock Car Brasil"),
    "Interlagos_Historic": ("Interlagos", "Historic 1976"),
    "Interlagos_Historic_Outer": ("Interlagos", "Historic 1976 Outer"),
    "InterlagosKart1": ("Interlagos", "Kart One"),
    "InterlagosKart2": ("Interlagos", "Kart Two"),
    "InterlagosKart3": ("Interlagos", "Kart Three"),
    "Jacarepagua_Historic": ("Jacarepaguá", "Historic 1988"),
    "Jacarepagua_2005": ("Jacarepaguá", "Historic 2005"),
    "Jacarepagua_OVAL": ("Jacarepaguá", "Historic 2005 Oval"),
    "Jacarepagua_SCB": ("Jacarepaguá", "Historic 2012 SCB"),
    "Jacarepagua_SHORT": ("Jacarepaguá", "Historic 2012 Short"),
    "Jerez_GP1988": ("Jerez", "Historic 1988"),
    "Jerez_GP2019": ("Jerez", "Moto"),
    "Jerez_Standard": ("Jerez", "Chicane"),
    "Kansai_GP": ("Suzuka", "Grand Prix"),
    "Kansai_Classic": ("Suzuka", "Classic"),
    "Kansai_East": ("Suzuka", "East"),
    "Kansai_West": ("Suzuka", "West"),
    "Kyalami_2019": ("Kyalami", "Grand Prix"),
    "Kyalami_Historic": ("Kyalami", "Historic 1976"),
    "Laguna_Seca_2020": ("Laguna Seca", "2020"),
    "Le_Mans_24h": ("Le Mans", "24 Hours"),
    "Le_Mans_24h_2005": ("Le Mans", "24 Hours 2005"),
    "Le_Mans_Circuit_Bugatti": ("Le Mans", "Circuit Bugatti"),
    "Londrina_short": ("Londrina", "Short"),
    "Londrina_long": ("Londrina", "Long"),
    "LondrinaKart1": ("Londrina", "Kart One"),
    "LondrinaKart2": ("Londrina", "Kart Two"),
    "Long_Beach": ("Long Beach", "Grand Prix"),
    "Long_Beach_STT": ("Long Beach", "STT"),
    "Montreal_Historic": ("Montréal", "Historic 1988"),
    "Montreal_Historic_1991": ("Montréal", "Historic 1991"),
    "Montreal_Modern": ("Montréal", "Grand Prix"),
    "Monza_1971_10k": ("Monza", "Historic 1971 10k"),
    "Monza_1971_10knc": ("Monza", "Historic 1971 10k (No Chicane)"),
    "Monza_1971": ("Monza", "Historic 1971"),
    "Monza_1991": ("Monza", "Historic 1991"),
    "Monza_1971_Junior": ("Monza", "Historic 1971 Junior"),
    "Monza_2005": ("Monza", "Historic 2005"),
    "Monza_2020": ("Monza", "Grand Prix"),
    "Monza_2020_Junior": ("Monza", "Junior"),
    "Monza_2020_STT": ("Monza", "STT"),
    "Mosport": ("Mosport", "Grand Prix"),
    "Nordschleife_2020": ("Nürburgring", "Nordschleife 2020"),
    "Nordschleife_2020_24hr": ("Nürburgring", "Nordschleife 24 Hour 2020"),
    "Nordschleife_2025": ("Nürburgring", "Nordschleife 2025"),
    "Nordschleife_2025_24hr": ("Nürburgring", "Nordschleife 24 Hour 2025"),
    "Nordschleife_2025_tourist": ("Nürburgring", "Nordschleife Tourist 2025"),
    "Nurb_GP_2020": ("Nürburgring", "GP 2020"),
    "Nurb_GP_2020_Veedol": ("Nürburgring", "Veedol 2020"),
    "Nurb_GP_2020_Sprint": ("Nürburgring", "Sprint 2020"),
    "Nurb_GP_2020_Sprint_S": ("Nürburgring", "Sprint S 2020"),
    "Nurb_GP_2025": ("Nürburgring", "GP 2025"),
    "Nurb_1971_Beton": ("Nürburgring", "Betonschleife Historic 1971"),
    "Nurb_1971_Gesamt": ("Nürburgring", "Gesamtstrecke Historic 1971"),
    "Nurb_1971_Nords": ("Nürburgring", "Nordschleife Historic 1971"),
    "Nurb_1971_Suds": ("Nürburgring", "Südscheleife Historic 1971"),
    "Nurb_2020_RX": ("Nürburgring", "Rallycross"),
    "Ortona1": ("Ortona", "Kart One"),
    "Ortona2": ("Ortona", "Kart Two"),
    "Ortona3": ("Ortona", "Kart Three"),
    "Ortona4": ("Ortona", "Kart Four"),
    "OultonPark_International": ("Oulton Park", "International"),
    "OultonPark_Classic": ("Oulton Park", "Classic"),
    "OultonPark_Fosters": ("Oulton Park", "Fosters"),
    "OultonPark_Island": ("Oulton Park", "Island"),
    "Pocono_OVAL": ("Pocono", "Oval"),
    "Pocono_RC1": ("Pocono", "East Course 1"),
    "Pocono_RC2": ("Pocono", "North/South Course 1"),
    "Pocono_RC3": ("Pocono", "North/South Course 1 (No Chicane)"),
    "Pocono_RC4": ("Pocono", "North/South Course 2"),
    "Pocono_RC5": ("Pocono", "Southeast Course 1"),
    "Pocono_RC6": ("Pocono", "Southeast Course 5"),
    "Road_America_RC": ("Road America", "Full"),
    "Road_America_RCB": ("Road America", "Bend"),
    "Road_America_STT": ("Road America", "STT"),
    "Road_Atlanta": ("Road Atlanta", "Full"),
    "Road_Atlanta_2005": ("Road Atlanta", "2005"),
    "Road_Atlanta_2005_short": ("Road Atlanta", "2005 Short"),
    "Road_Atlanta_Moto": ("Road Atlanta", "Moto"),
    "Salvador_Street_Circuit": ("Salvador", "Street Circuit"),
    "SantaCruzDoSul": ("Santa Cruz do Sul", "Full"),
    "Sebring": ("Sebring", "Full"),
    "Sebring_Club": ("Sebring", "Club"),
    "Sebring_School": ("Sebring", "School"),
    "Sebring_STT": ("Sebring", "STT"),
    "Silverstone_1975": ("Silverstone", "Historic 1975"),
    "Silverstone_1975_No_Chicane": ("Silverstone", "Historic 1975 (No Chicane)"),
    "Silverstone_1991": ("Silverstone", "Historic 1991"),
    "Silverstone_2001": ("Silverstone", "Historic 2001"),
    "Silverstone_2001_International": ("Silverstone", "International Historic 2001"),
    "Silverstone_2001_National": ("Silverstone", "National Historic 2001"),
    "Silverstone_GP": ("Silverstone", "Grand Prix"),
    "Silverstone_Intl_2019": ("Silverstone", "International"),
    "Silverstone_Natl_2019": ("Silverstone", "National"),
    "Snetterton_100": ("Snetterton", "100"),
    "Snetterton_200": ("Snetterton", "200"),
    "Snetterton_300": ("Snetterton", "300"),
    "Spa_Francorchamps_1970": ("Spa-Francorchamps", "1970"),
    "Spa_Francorchamps_1970_1000km": ("Spa-Francorchamps", "1970 1000km"),
    "Spa_Francorchamps_1993": ("Spa-Francorchamps", "1993"),
    "Spa_Francorchamps_2005": ("Spa-Francorchamps", "2005"),
    "Spa_Francorchamps_2005_EC": ("Spa-Francorchamps", "2005 Endurance"),
    "Spa_Francorchamps_2020": ("Spa-Francorchamps", "2020"),
    "Spa_Francorchamps_2022": ("Spa-Francorchamps", "2022"),
    "Spa_Francorchamps_2022_RX": ("Spa-Francorchamps", "Rallycross"),
    "Speedland1": ("Speedland", "Kart 1"),
    "Speedland2": ("Speedland", "Kart 2"),
    "Speedland3": ("Speedland", "Kart 3"),
    "Speedland4": ("Speedland", "Kart 4"),
    "Spielberg_2001": ("Red Bull Ring", "Historic 2001"),
    "Spielberg_Historic": ("Red Bull Ring", "Historic 1977"),
    "Spielberg_Vintage": ("Red Bull Ring", "Historic 1974"),
    "Spielberg_Modern": ("Red Bull Ring", "Grand Prix"),
    "Spielberg_Short": ("Red Bull Ring", "Short"),
    "Spielberg_STT": ("Red Bull Ring", "STT"),
    "Taruma_Internacional": ("Tarumã", "International"),
    "Taruma_Chicane": ("Tarumã", "Chicane"),
    "Termas_Rio_Hondo": ("Termas de Río Hondo", "Full"),
    "Tykki_Dirt1": ("Tykki", "Dirt 1"),
    "Tykki_Dirt2": ("Tykki", "Dirt 2"),
    "Tykki_RX": ("Tykki", "Rallycross"),
    "Tykki_Tarmac": ("Tykki", "Tarmac"),
    "VeloCitta1": ("Velo Cittá", "Full"),
    "VeloCittaTD": ("Velo Cittá", "Track Day"),
    "VeloCittaClubDay": ("Velo Cittá", "Club Day"),
    "Velopark_2010": ("Velopark", "2010"),
    "Velopark_2017": ("Velopark", "2017"),
    "Velopark_2017_STT": ("Velopark", "2017 STT"),
    "Virginia_Full": ("Virginia International Raceway", "Full"),
    "Virginia_Grand": ("Virginia International Raceway", "Grand"),
    "Virginia_North": ("Virginia International Raceway", "North"),
    "Virginia_Patriot": ("Virginia International Raceway", "Patriot"),
    "Virginia_South": ("Virginia International Raceway", "South"),
    "Watkins_Glen_GP": ("Watkins Glen", "Grand Prix"),
    "Watkins_Glen_GPIL": ("Watkins Glen", "GP (Inner Loop)"),
    "Watkins_Glen_S": ("Watkins Glen", "Short"),
    "Watkins_Glen_SIL": ("Watkins Glen", "Short (Inner Loop)"),
    "Watkins_Glen_STT": ("Watkins Glen", "STT"),
}


def _fallback_meta(code: str) -> tuple[str, str]:
    parts = code.replace("_", " ").split()
    if len(parts) == 1:
        return parts[0], "Full"
    return parts[0], " ".join(parts[1:])


def main() -> None:
    codes = json.loads(TRACKS_JSON.read_text(encoding="utf-8"))
    missing: list[str] = []
    payload: dict[str, dict[str, str]] = {}
    for code in codes:
        if code in META:
            venue, layout = META[code]
        else:
            missing.append(code)
            venue, layout = _fallback_meta(code)
        payload[code] = {"venue": venue, "layout": layout}

    OUT_JSON.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Wrote {len(payload)} entries to {OUT_JSON}")
    if missing:
        raise SystemExit(f"Missing explicit meta for: {', '.join(missing)}")


if __name__ == "__main__":
    main()
